# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
  tags:
    include:
    - v*

pr: none

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'x86'
  buildConfiguration: 'Release'


steps:
- task: UseDotNet@2
  displayName: Install .NET Core 3.0
  inputs:
    packageType: 'sdk'
    version: '3.0.x'

- task: DotNetCoreCLI@2
  displayName: Build projects
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '-c $(buildConfiguration)'

#自己完結型
- task: DotNetCoreCLI@2
  displayName: Create build self-contained artifact
  inputs:
    command: publish    
    publishWebProjects: false
    projects: '**/BGMPlayer.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.BinariesDirectory) -r win10-x86 --self-contained true /p:PublishSingleFile=true'
    zipAfterPublish: false
    modifyOutputPath: false

- task: CopyFiles@2
  displayName: copy self-contained document
  inputs:
    contents: |
      $(Build.SourcesDirectory)/**/BGMPlayer/README.txt
      $(Build.SourcesDirectory)/**/BGMPlayer/使用したライブラリ.txt
    targetFolder: $(Build.BinariesDirectory)
    flattenFolders: true


- task: ArchiveFiles@2
  displayName: Create self-contained zip 
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)' 
    includeRootFolder: false 
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/BGMPlayer_runtime_bundle.zip' 

#ポータブル
- task: DotNetCoreCLI@2
  displayName: Create build artifact
  inputs:
    command: publish    
    publishWebProjects: false
    projects: '**/BGMPlayer.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.BinariesDirectory) -r win10-x86 --self-contained false /p:PublishSingleFile=true'
    zipAfterPublish: false
    modifyOutputPath: false


- task: CopyFiles@2
  displayName: copy document
  inputs:
    contents: |
      $(Build.SourcesDirectory)/**/BGMPlayer/README.txt
      $(Build.SourcesDirectory)/**/BGMPlayer/使用したライブラリ.txt
    targetFolder: $(Build.BinariesDirectory)
    flattenFolders: true

- task: ArchiveFiles@2
  displayName: Create zip 
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)' 
    includeRootFolder: false 
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/BGMPlayer.zip' 

# GitHubにUpload
- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'dorisol1019-2'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'gitTag'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'

